COMMON_SRC = parallel.c
PROGS = parallel-one.c parallel-two.c

# uncomment if you want it to automatically run.
RUN=0

LIBS += $(CS140E_2024_PATH)/lib/libgcc.a

BOOTLOADER = my-install
EXCLUDE ?= grep -v simple_boot
include $(CS140E_2024_PATH)/libpi/mk/Makefile.robust